services:
  - type: web
    name: bergas
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
